# Configuración del plugin Soldado
# Este archivo almacena la configuración persistente del NPC

# Configuración del NPC 
npc:
  name: "Soldado"
  skin: "saku328"

# Configuración de las coordenadas de los waypoints
# Las coordenadas están en formato "x,y,z"
waypoints:
  - "-41,63,46"
  - "-49,63,46"
  - "-49,63,40"
  - "-53,63,36"
  - "-41,63,36"