# Configuración del plugin Soldado
# Este archivo almacena la configuración persistente del NPC

# Configuración del NPC (se llena automáticamente)
npc:
  # ID del NPC (automático)
  # puntoA: ubicación del punto A (automático) 
  # puntoB: ubicación del punto B (automático)

# Configuraciones opcionales
settings:
  patrol-distance: 12.0
  detection-range: 5.0
  check-interval: 100