name: Soldado
version: 1.0
main: edu.vic.Soldado
api-version: 1.20
depend: [Citizens]
commands:
  crearnpc:
    description: Crea un NPC con IA básica
    usage: /crearnpc
  eliminarnpcs:
    description: Elimina todos los NPCs 
    usage: /eliminarnpcs
  iniciarpatrullaje:
    description: Inicia el patrullaje del NPC
    usage: /iniciarpatrullaje