name: Soldado
version: 1.0
main: edu.vic.Soldado
api-version: 1.20
depend: [Citizens]
commands:
  crearnpc:
    description: Crea un NPC con IA básica
    usage: /crearnpc
  eliminarnpcs:
    description: Elimina todos los NPCs 
    usage: /eliminarnpcs
  iniciarpatrullaje:
    description: Inicia el patrullaje del NPC
    usage: /iniciarpatrullaje
  recargarconfig:
    description: Recarga la configuración del NPC desde el archivo config.yml
    usage: /recargarconfig
  menustart:
    description: Inicia el menu Start
    usage: /menustart
  eliminarhologramas:
    description: Elimina los hologramas que se acaban de crear
    usage: /eliminarhologramas
  eliminartodoholograma:
    description: Elimina todos los hologramas 
    usage: /eliminartodoholograma
  crearmenuvertical:
    description: Crea el menú vertical
    usage: /crearmenuvertical